@startuml
skinparam componentStyle uml2

[Экран\n"Карта"]
[Экран\n"Редактирование\nадреса"]

[Экран\n"Презентация"] -down-> [Экран\n"Вход"]
[Экран\n"Вход"] -> [Экран\n"Ввод кода\nподтверждения"]
[Экран\n"Ввод кода\nподтверждения"] -> [Экран\n"Вход"]
[Экран\n"Ввод кода\nподтверждения"] -down-> [Экран\n"Разделы меню"]
[Экран\n"Ввод кода\nподтверждения"] -down-> [Экран\n"Выбор населенного\nпункта"]
[Экран\n"Выбор населенного\nпункта"] -down-> [Экран\n"Разделы меню"]

[Экран\n"Выбор населенного\nпункта"] -down-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -up-> [Экран\n"Выбор населенного\nпункта"]

[Экран\n"Выбор населенного\nпункта"] -down-> [Экран\n"Карта"]
[Экран\n"Карта"] -up-> [Экран\n"Выбор населенного\nпункта"]

[Экран\n"Разделы меню"] -right-> [Экран\n"Витрина"]
[Экран\n"Витрина"] -left-> [Экран\n"Разделы меню"]
[Экран\n"Витрина"] -down-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -up-> [Экран\n"Витрина"]
[Экран\n"Витрина"] -down-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -up-> [Экран\n"Витрина"]
[Экран\n"Витрина"] -right-> [Экран\n"Профайл\nпродукта"]
[Экран\n"Профайл\nпродукта"] -left-> [Экран\n"Витрина"]
[Виджет\n"Статус заказа"] -down-> [Экран\n"Витрина"]
[Экран\n"Витрина"] -> [Экран\n"Витрина"]

[Экран\n"Корзина"] -left-> [Экран\n"Опции продукта"]
[Экран\n"Опции продукта"] -right-> [Экран\n"Корзина"]
[Экран\n"Витрина"] -down-> [Экран\n"Опции продукта"]
[Экран\n"Опции продукта"] -up-> [Экран\n"Витрина"]

[Экран\n"Профайл\nпродукта"] -down-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -up-> [Экран\n"Профайл\nпродукта"]
[Экран\n"Профайл\nпродукта"] -down-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -up-> [Экран\n"Профайл\nпродукта"]

[Экран\n"Настройки"] -down-> [Экран\n"Информация\nо приложении"]
[Экран\n"Информация\nо приложении"] -up-> [Экран\n"Настройки"]

[Экран\n"Корзина"] -down-> [Экран\n"Заказ"]
[Экран\n"Заказ"] -up-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -down-> [Экран\n"Выбор\nподарка"]
[Экран\n"Выбор\nподарка"] -up-> [Экран\n"Корзина"]

[Экран\n"Корзина"] -down-> [Экран\n"Карта"]
[Экран\n"Карта"] -up-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -down-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -up-> [Экран\n"Корзина"]

[Экран\n"Заказ"] -down-> [Экран\n"Карта"]
[Экран\n"Карта"] -up-> [Экран\n"Заказ"]
[Экран\n"Заказ"] -down-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -up-> [Экран\n"Заказ"]

[Экран\n"Настройки"] -left-> [Экран\n"Карта"]
[Экран\n"Карта"] -right-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -left-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -right-> [Экран\n"Настройки"]

[Экран\n"Вход"] -> [Экран\n"Пользовательское\nсоглашение"]
[Экран\n"Пользовательское\nсоглашение"] -> [Экран\n"Вход"]
[Экран\n"Настройки"] -up-> [Экран\n"Пользовательское\nсоглашение"]
[Экран\n"Пользовательское\nсоглашение"] -down-> [Экран\n"Настройки"]

@enduml