@startuml
skinparam componentStyle uml2

[Экран\n"Карта"]
[Экран\n"Редактирование\nадреса"]

[Экран\n"Презентация"] -down-> [Экран\n"Вход"]
[Экран\n"Вход"] -> [Экран\n"Ввод кода\nподтверждения"]
[Экран\n"Ввод кода\nподтверждения"] -> [Экран\n"Вход"]
[Экран\n"Ввод кода\nподтверждения"] -down-> [Экран\n"Разделы меню"]
[Экран\n"Ввод кода\nподтверждения"] -down-> [Экран\n"Выбор города"]
[Экран\n"Выбор города"] -down-> [Экран\n"Разделы меню"]

[Экран\n"Разделы меню"] -right-> [Экран\n"Лента товаров"]
[Экран\n"Лента товаров"] -left-> [Экран\n"Разделы меню"]
[Экран\n"Лента товаров"] -down-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -up-> [Экран\n"Лента товаров"]
[Экран\n"Лента товаров"] -down-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -up-> [Экран\n"Лента товаров"]
[Экран\n"Лента товаров"] -right-> [Экран\n"Профайл\nпродукта"]
[Экран\n"Профайл\nпродукта"] -left-> [Экран\n"Лента товаров"]
[Виджет\n"Статус заказа"] -down-> [Экран\n"Лента товаров"]
[Экран\n"Лента товаров"] -> [Экран\n"Лента товаров"]

[Экран\n"Профайл\nпродукта"] -down-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -up-> [Экран\n"Профайл\nпродукта"]
[Экран\n"Профайл\nпродукта"] -down-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -up-> [Экран\n"Профайл\nпродукта"]

[Экран\n"Настройки"] -right-> [Экран\n"Информация\nо приложении"]
[Экран\n"Информация\nо приложении"] -left-> [Экран\n"Настройки"]

[Экран\n"Корзина"] -down-> [Экран\n"Заказ"]
[Экран\n"Заказ"] -up-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -down-> [Экран\n"Опции\nприобретаемого\nпродукта"]
[Экран\n"Опции\nприобретаемого\nпродукта"] -up-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -down-> [Экран\n"Выбор\nподарка"]
[Экран\n"Выбор\nподарка"] -up-> [Экран\n"Корзина"]

[Экран\n"Корзина"] -down-> [Экран\n"Карта"]
[Экран\n"Карта"] -up-> [Экран\n"Корзина"]
[Экран\n"Корзина"] -down-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -up-> [Экран\n"Корзина"]

[Экран\n"Заказ"] -down-> [Экран\n"Карта"]
[Экран\n"Карта"] -up-> [Экран\n"Заказ"]
[Экран\n"Заказ"] -down-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -up-> [Экран\n"Заказ"]

[Экран\n"Настройки"] -left-> [Экран\n"Карта"]
[Экран\n"Карта"] -right-> [Экран\n"Настройки"]
[Экран\n"Настройки"] -left-> [Экран\n"Редактирование\nадреса"]
[Экран\n"Редактирование\nадреса"] -right-> [Экран\n"Настройки"]

@enduml