@startuml
skinparam componentStyle uml2

package "Система" {
    package "Веб-сервис" {
        HTTP - [REST Веб-сервис\nс базой данных\nв оперативной памяти]
    }

    [iOS/Android приложение] -up--> HTTP

    [Telegram-бот\nдля администрирования\nи модерирования] -up--> HTTP
}

cloud {
    [iOS/Android приложение] -> Digits
    [iOS/Android приложение] -> YandexMaps
    [iOS/Android приложение] -> IpApi
    [iOS/Android приложение] -> Autocomple
    [Telegram-бот\nдля администрирования\nи модерирования] -down--> TelegramApi
    TelegramApi -up--> [Telegram-бот\nдля администрирования\nи модерирования]
}

@enduml