@startuml
skinparam componentStyle uml2

package "Система" {
    package "Веб-сервис" {
        HTTP - [REST Веб-сервис,\nTelegram-бот]
    }

    [iOS/Android приложение] -up--> HTTP
}

cloud {
    [iOS/Android приложение] -> Digits
    [iOS/Android приложение] -> YandexMaps
    [iOS/Android приложение] -> IpApi
    [iOS/Android приложение] -> Autocomple
    Telegram -up--> HTTP
    [REST Веб-сервис,\nTelegram-бот] -down--> Telegram
}

@enduml